extensions/cpsection/backup/view.py
In backup cp section
Fixes #4820
=> Use 'retrieve' instead of 'retrive'

extensions/cpsection/aboutcomputer/view.py
We have made changes in 2015, so I think we can change it :smile:
=> Update copyright date to 2015 in my settings

extensions/cpsection/aboutcomputer/model.py, src/jarabe/model/network.py
Replaces https://github.com/sugarlabs/sugar/pull/495
This is a refactoring of the patch provided by James Cameron [1]
to use it in Sugar upstream.
Is compatible with XO or other devices.
[1] http://lists.sugarlabs.org/archive/sugar-devel/2015-April/049970.html
=> Revert nm introspection try2

data/org.sugarlabs.gschema.xml, extensions/cpsection/network/model.py, extensions/cpsection/network/view.py, src/jarabe/view/palettes.py, src/jarabe/view/viewhelp.py
Replaces #494 
Requires https://github.com/sugarlabs/sugar-artwork/pull/50
Changes:
* Add loading/flashing icon
* Deal with edge case for users with no server configured
* Bug fixes for @godiard's comments
=> Socialhelp popup try4

extensions/cpsection/updater/view.py, src/jarabe/desktop/activitieslist.py, src/jarabe/journal/expandedentry.py, src/jarabe/journal/listview.py, src/jarabe/journal/objectchooser.py
Use the performance implementations in https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/219
Replaces https://github.com/sugarlabs/sugar/pull/509
=> Treeview perf3

src/jarabe/view/viewsource.py
Using the api introduced in da72c3b
=> Refactor view source to use activity.has_shell_window

src/jarabe/main.py
Replaces https://github.com/sugarlabs/sugar/pull/543
=> main.py: Rename setup_locale to setup_timezone

extensions/cpsection/aboutme/view.py, extensions/cpsection/webaccount/view.py, src/jarabe/desktop/favoritesview.py, src/jarabe/intro/agepicker.py, src/jarabe/intro/genderpicker.py, src/jarabe/journal/expandedentry.py
This patch complement the fix for #4863 using the 'activate' event created in https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/242
=> Check mouse position activate

src/jarabe/view/viewsource.py
*Let's make sugar 108 the most paletteable release ever!*
=> Use Sugar palette menus for view source, not Gtk.Menu

src/jarabe/view/viewsource.py
This patch adds a Confirmation alert when Duplicate (in view source)
is clicked.
Also adds a "Copying" alert, that is showed when the copy start
until it finish.
By Sam:
Added alerts for when the Duplicate activity already exists
and after the activity is duplicated
Fixes #3672
=> Confirmation alert and Copying alert for Duplicate  in source view

bin/sugar.in
Remove stray single quote.
End sentence with a period.
=> sugar.in:  Fix typos in the debug file here document.

extensions/cpsection/frame/view.py
Fix for Sam being able to hit buttons quickly. ;-)
=> frame control panel slider apply

bin/sugar.in
Pushing upstream a downstream patch that has general applicability.
Borrowed from
https://anonscm.debian.org/cgit/pkg-sugar/sugar.git/
Signed-off-by: James Cameron <quozl@laptop.org>
=> sugar.in: fix shell posix and quoting

src/jarabe/model/brightness.py
Path resolution is automatically handled by pkexec
#605 was merged without PATH resolution as well
=> Remove path resolution for sugar-backlight-{setup,helper}

src/jarabe/desktop/favoriteslayout.py, src/jarabe/desktop/meshbox.py, src/jarabe/desktop/networkviews.py, src/jarabe/view/buddyicon.py
* Neighborhood icons are placed according to their data
* Bug ticket 381 (https://bugs.sugarlabs.org/ticket/381)
* This is a GCI 2015 task: https://codein.withgoogle.com/tasks/6733138625560576/
=> Neighborhood icons are no longer placed randomly

po/ru.po
Hi everybody,
I really like this project and I'd like to improve it further.
=> Fixed some russian strings and translated new ones.

extensions/cpsection/aboutme/model.py
Also, this function doesn't look like it's used anywhere?
=> Confuses i18n efforts

src/jarabe/view/buddymenu.py
Ticket url:  https://bugs.sugarlabs.org/ticket/4959
=> Don't contruct ActivityBundle for the journal, fixes #4959

src/jarabe/desktop/transitionbox.py, src/jarabe/frame/frame.py
The toolkit part of this feature was merged recently.  This is a very small patch to make use of the additions in jarabe
Feature: http://wiki.sugarlabs.org/go/Features/Tick_based_animation
=> Smooth animations try 4

src/jarabe/view/viewhelp.py
This allows the user to navigate, so that they do not get lost
if they click a hyperlink that takes them off the social help
website.  It also helps users feel safe if navigating the help
documentation, as they will not get lost.
https://bugs.sugarlabs.org/ticket/4913
=> Add forward and back buttons in help view, fixes #4913

src/jarabe/journal/objectchooser.py
sugar-toolkit-gtk3 a803876: Added new popwindow module in sugar3.graphics
=> Refactor journal.objectChooser according to popup module in toolkit-gtk3

extensions/cpsection/aboutcomputer/model.py, extensions/cpsection/aboutcomputer/view.py
Fixes for several problems with About My Computer control panel on Fedora and Ubuntu.
OLPC note: has been sent to manufacturing of SKU400, though with a more detailed hardware specific patch also applied.
=> About my computer fixes

extensions/cpsection/language/view.py
Fixes for several problems on Fedora and Ubuntu, refer to the individual commit messages for details.
OLPC note: has been sent to manufacturing of SKU400.
=> Language control panel fixes

src/jarabe/frame/activitiestray.py, src/jarabe/frame/notification.py, src/jarabe/journal/journaltoolbox.py, tests/views/journal_detailstoolbox.py
As noted by Abhijit in
https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/90cec5be2eb82024f4a7115059304021b19c5318#commitcomment-18615765
=> Do not use the deprecated Palette.popdown state argument

extensions/deviceicon/network.py
Frame network device icon palette is to show IP address, but it lags or is wrong.  Testing with NetworkManager 1.2.2 and 1.2.4 showed;
* wireless initially `0.0.0.0`, but when the signal strength changes several seconds later the IP address assigned by DHCP is shown,
* ad-hoc with no peers never shows IP address, always `0.0.0.0`, even though an address is assigned,
* wired ethernet never shows IP address, always `0.0.0.0`.
The problem is in NetworkManager, and Sugar is showing whatever NetworkManager provides as the `Ip4Address` property for the interface object.
However, the `Ip4Address` property has been deprecated.  It may be that being deprecated, the `Ip4Address` property is no longer well maintained, or intentionally delayed, and we might not be able to get it fixed upstream.
This …
=> Frame, Network Device icons: IP address

src/jarabe/controlpanel/gui.py, src/jarabe/journal/objectchooser.py, src/jarabe/view/keyhandler.py, src/jarabe/view/viewhelp.py, src/jarabe/view/viewsource.py
Several fixes for control panel, view source, and view help, cherry-picked from the OLPC branch.
Reviewers please read the commit description of each commit in the pull request; 739993b, 305a2ee and 0a41a82.
=> Modal dialog fixes

src/jarabe/main.py
Fixes https://bugs.sugarlabs.org/ticket/4958
Supersedes https://github.com/sugarlabs/sugar/pull/682
=> Restart metacity if it fails

src/jarabe/journal/listmodel.py
- situation is normal,
- probably left-over debugging.
=> Remove an error from log

src/jarabe/desktop/favoritesview.py
With reference to https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/395
Tested on: rdesktop, Ubuntu 16.04
=> update datastore signal handler

src/jarabe/journal/journalactivity.py
Journal covers Home View on startup when Metacity is 3.25.1 or later, isolated to Metacity [6875256](https://github.com/GNOME/metacity/commit/6875256e63fbfd4500ddd27a7bf1aafc8d4c1ca3) ("unminimize windows with initial IconicState if first known on MapRequest").
Detect the window state event where ICONIFIED is cleared without any action by the user.  Repeat the iconify request.
Has side-effect of showing a Metacity iconify animation, but this is better than not fixing it.
Fixes https://github.com/sugarlabs/sugar/issues/769
Fixes https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/368
Tested on Fedora 18 and Ubuntu 16.04; does not trigger.
Tested on Ubuntu 18.04; does trigger.
=> Journal - iconify again if Metacity misbehaves (RHBZ #1519042)

README.md
Unwanted Dependencies was mentioned. Most of it automatically installed. Links to dependencies was added;
=> Readme.md updated to add links to dependencies.

src/jarabe/main.py
Fixes #872 & Fixes #827 
@walterbender @quozl  Please review
=> Restore GNOME cursor theme on sugar DE exit

src/jarabe/model/adhoc.py, src/jarabe/model/network.py
=> fix unicode issues in ssid handling

src/jarabe/journal/expandedentry.py, src/jarabe/journal/journalactivity.py, src/jarabe/journal/journaltoolbox.py, src/jarabe/journal/listview.py
Existed as #791. @quozl @srevinsaju @sourabhaa @sparshg kindly test and review.
=> Feature accessibility journal

src/jarabe/desktop/favoritesview.py
Noticed this while looking at #739 and marked as draft since that hasn't been merged, @quozl if you think this shouldn't be a draft please let me know.
=> Remove instance check

configure.ac, src/jarabe/util/downloader.py, src/jarabe/view/viewhelp_webkit2.py, tests/test_downloader.py
Fixes #974, @quozl kindly review.
=> Web kit2 4.1

.github/workflows/weblate-sync.yaml
This will automatically open a PR whenever weblate pushes changes to weblate-sync.
=> Add weblate sync workflow

po/ms.po
I have updated some of the translations for SUGAR
=> translate to malay

po/ka.po
=> Translated using Weblate (Georgian)

.well-known/funding-manifest-urls
In order for this to validate our schema, we would need to have this structure .
https://github.com/sugarlabs/www/pull/679
As present in the guidelines:
https://floss.fund/funding-manifest/
=> floss fund estabhlishment
