sugarlabs/sugar

src/jarabe/frame/activitiestray.py
Changed "canceled" --> "cancelled".
File affected sugar/src/jarabe/frame/activitiestray.py
Fixes #4823
=> Modified typo in sugar

extensions/cpsection/network/view.py, src/jarabe/controlpanel/gui.py
Right now the jabber server entry autosaves when the user presses enter.
With this patch, that no longer happens. The user must click the accept
button in the control panel in order to save a new jabber server entry.
The timeout has been removed because we need now reset the server immediately
when the accept button is pressed.
The change-signal handler has been removed because we only want to change the
server name when the user clicks on accept button.
An apply flag has been added so if the user clicks on accept, we know
whether or not the server should be updated.
=> Don't save jabber without user confirmation.

extensions/cpsection/language/model.py
My Settings Language showed English USA on XO-4 laptops with LO tag set
to es_UY.UTF-8 and Spanish keyboards.  It should show Spanish Uruguay.
Workaround is to ignore what is shown and change it.
Cause was unhandled newline when reading $HOME/.i18n file.  As a result,
following code to convert UTF-8 to utf8 did not run, and so the language
setting could not be found in "locale -av" output.  The default language
setting was used.
Fix is to strip the whitespace from the end of the line.
Reported-by: Walter Bender <walter.bender@gmail.com>
Reported-by: Samuel Greenfeld <samuel@greenfeld.org>
Signed-off-by: James Cameron <quozl@laptop.org>
=> fix language control panel on XO es_UY keyboards

src/jarabe/intro/window.py
When the user press Return, we need check if the page is in a valid state
before checking if is the last page.
=> Age picker: check if is in a valid state - Fixes #4850

src/jarabe/main.py, src/jarabe/model/screen.py
Rework of previous https://github.com/sugarlabs/sugar/pull/478
Sugar asks olpc-powerd to unfreeze the display once startup is complete.  On platforms without olpc-powerd, this causes:
```
ERROR dbus.proxies: Introspect error on org.freedesktop.ohm:/org/freedesktop/ohm/Keystore:
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name
org.freedesktop.ohm was not provided by any .service files
ERROR root: Cannot unfreeze the DCON
```
Remove this logging, by detecting powerd before resolving the interface.
Remove the DCON concept from main.py, by changing method names, so that the implementation details are hidden in model/screen.py
Tested on XO-1 with Fedora 18.
Tested on commodity hardware with Ubuntu 14.04.2 LTS (Trusty).
=> Avoid "Cannot unfreeze the DCON"

.gitignore, bin/Makefile.am, bin/sugar-backlight-helper, bin/sugar-backlight-setup, data/Makefile.am, data/org.sugar.brightness.policy.in, data/org.sugarlabs.gschema.xml, extensions/deviceicon/Makefile.am, extensions/deviceicon/display.py, extensions/globalkey/Makefile.am, extensions/globalkey/brightness.py, extensions/globalkey/screenshot.py, po/POTFILES.in, po/POTFILES.skip, src/jarabe/model/Makefile.am, src/jarabe/model/brightness.py, src/jarabe/model/screenshot.py
This PR is for adding brightness control capabilities to Sugar. It includes a generic mechanism to interact with backlight devices, a jarabe model that acts as an abstraction for the sugar shell, keyboard control keys and a device frame UI.
=> Brightness controls try9

src/jarabe/desktop/activitieslist.py, src/jarabe/journal/keepicon.py, src/jarabe/journal/listview.py
Change the star color on hovering cnfuses to the user,
because think the favorite state has changed.
This can be seen in the activities list view, in the Journal listview,
and in the Journal detail view.
=> Don't change star color on hovering - Fixes #3147

extensions/cpsection/aboutcomputer/model.py
On most XO laptops the firmware version doesn't have the engineer's build number appended, and this results in "Q7C05   with 0.5.01" shown.  Oh the irony.
Strip the trailing whitespace before using the version number.
=> Fix trailing whitespace on firmware version

src/jarabe/view/viewhelp.py
For consistency with other modal dialogs such as view source and control panel, add a handler to translate escape key into stop button.
Tested on XO-4 with 14.1.0 and Sugar 0.105.1, using this method:
* change file on target, restart display manager:
```
rsync src/jarabe/view/viewhelp.py \
target:/usr/lib/python2.7/site-packages/jarabe/view/viewhelp.py
ssh target service olpc-dm restart
```
* start Implode activity, use Alt-Shift-H to display help window,
* press Escape, and window does close,
* check for interesting logs.
=> Add escape key to close help

src/jarabe/main.py
This commit disables overlay scrolling in Sugar.  Although this should
be set in the sugar theme, that is not possible.
Setting the environment variable disables the overlay scrolling for
both Sugar Shell and all sub processes (eg. activities).
By setting an environment variable, this is ignored by Gtk versions
less than 3.16.
Ticket URL:  http://bugs.sugarlabs.org/ticket/4854
=> Disable overlay scrolling, fixes #4854

src/jarabe/model/brightness.py
Watch the specific brightness file instead of watching the whole
device directory and drop the use of WATCH_HARD_LINKS because is
not necessary.
This patch fixes the brightness monitor in Fedora 18.
Signed-off-by: Martin Abente Lahaye <tch@sugarlabs.org>
=> Fix brightness monitor flags and file

src/jarabe/main.py
Load the brightness module earlier in the shell startup process
in order to restore the brightness level before any other screen
shows up, ie., the intro screen.
Signed-off-by: Martin Abente Lahaye <tch@sugarlabs.org>
=> Restore brightness level earlier in startup

extensions/cpsection/power/__init__.py, src/jarabe/controlpanel/gui.py
On commodity hardware the power control panel does nothing useful.
With this patch, if powerd is not present, the CLASS global is not set, causing the panel to be omitted from the control panel.
The message about missing CLASS is demoted from error to debug.
Tested on Ubuntu 15.04 Vivid with Sugar 0.105.2 (without powerd) and Fedora 18 with Sugar 0.104.1 (with powerd).
=> Hide power control panel if powerd missing

src/jarabe/desktop/activitieslist.py
Use different Gtk.TreeViewColumn for each favorite column,
otherwise only the fist one can be clicked and prevents
populating the other home views.
Slightly cleanup that code.
Signed-off-by: Martin Abente Lahaye <tch@sugarlabs.org>
=> Fix favorite selection in multiple home views

src/jarabe/model/bundleregistry.py
BundleRegistry uses Gio.FileMonitor to track changes in activity
installation directories. Any changes in these directories will be
detected and processed by the BundleRegistry.
When processed, the registry will simply assume it is a new bundle
and it will use "bundle_from_dir" helper to load it. The helper
has 3 potential results, (a) it returns a bundle, (b) it throwns
an exception if something went wrong while loading the bundle, or
(c) returns None if the directory is not a bundle.
BundleRegistry.add_bundle did not covered the case (c), therefore
it was failing when non-bundle directories were creates. E.g, when
package managers (such as dpkg) creates temporary directories.
This patch add an extra check to cover the missing case (c) from
when the "bundle_from_dir" helper. …
=> Fix logic hole in BundleRegistry.add_bundle

src/jarabe/model/shell.py, src/jarabe/view/viewhelp.py
If a user press multiple times the view help shortcut (Alt+Shift+H)
we need check if a window is opened before open another.
The bug was the result of check on a different windows array.
=> Do not open multiple help windows - Fixes #4799

src/jarabe/journal/journaltoolbox.py
Some strings in the Journal are never translated, even when there are proper translations in the .PO.
To test:
1. Go to CP and switch language to Spanish (restart shell).
2. Once in Sugar again, go to Journal and click on Sort tool button.
Without this patch, only english strings can be seen. With the patch, the strings are properly translated.
EXTRA: Fixed a pep8 warning in that file, in a separate commit.
=> Fix journal translations try1

src/jarabe/journal/listview.py
The GtkTreeDragSource is not working for us, without changes in the
docs.  This commit uses the ListView as a proxy for the old methods.
This patch is based in work from Sam Parkinson <sam.parkinson3@gmail.com>
and was tested on F18 and F22.
=> Fix Journal ListView DnD, fixes #4853

src/jarabe/main.py
One example solved by this patch are the generic mime type names
displayed in the 'What' filter in the Journal.
These names are defined in mime.py in the toolkit, and loaded at import time.
=> Earlier gettext initialization to asure translations are loaded

src/jarabe/view/viewhelp.py
We need check if another window is opened before open the help window.
When the help is related to a activity, is already solved
checking activity.has_shell_window(), but if is in the Home View,
we need avoid open when the My Settings window is opened.
This patch solve the last case.
=> Help window: check if another window is opened - Fixes 4801

extensions/cpsection/language/model.py
If the file is empty or corrupted, use the default language.
=> Set default language when read .i18n file - Fixes #4868

extensions/cpsection/language/model.py, extensions/cpsection/language/view.py, src/jarabe/controlpanel/inlinealert.py
Replaces https://github.com/sugarlabs/sugar/pull/558 addressing comments from @quozl.
=> More robust i18n try4

src/jarabe/model/filetransfer.py
When the journal palettes are being created, it checks whether
or not there are friends to be added to the send-to menu. This
check is being done via the file_transfer_available helper.
The helper uses the telepathy connection watcher and, under some
circunstances that I haven't been able to reproduce, the connections
in the watcher cannot be reached via the DBus interface.
When this happens, an unhandled DBusException is thrown, breaking
the palette. In other words, the journal palettes are not being
displayed anymore until the shell session is restarted.
This issue was noticed running on Ubuntu 14.04. Created a ticket to
track the source of this issue in SL#4887.
This patch improves the robustness of this helper, but it logs the error
so we don't loose track of this issue. …
=> Fix journal palettes when missing contact connection

src/jarabe/view/viewsource.py
Finally tested on sugar-build.
I get errors, but I think it's not because of this patch.
I need to look on the mechanism of duplication.
=> Use busy cursor when duplicating activities

src/jarabe/view/customizebundle.py
This fixes a crash during the duplicate function in view source.
Steps to reproduce:
1. Open view source for an activity
2. Duplicate
3. See error in shell.log
4. See that there wasn't an xo bundle created in the journal
@i5o, does this fix your issue in sugar-build?
Note to self:  reopen https://github.com/samdroid-apps/sugar/commit/63348be2485a8b84f321fedc322715f3678f4399 after merge
=> Ensure duplicated xo bundle is placed in expected directory

src/jarabe/journal/listmodel.py, src/jarabe/journal/listview.py
Implement a set_value method in the model, and move the logic
to write to the datastore to the ListModel. To be able to
update the model without trigger a update in the treeview,
we pass the updated callback in the ListModel.setup() method,
and the callback is disconnected and connected in every update.
The treeview have the responsabilty of redraw the cell after
the change was done.
The listmodel stores a dictionary with the entries uodated,
to provide that data until the next update in the Journal.
This patch is heavily based in the work of
Sam Parkinson <sam.parkinson3@gmail.com>
=> Update metadata in the treeview without reload all - Fixes #4852

src/jarabe/journal/journalactivity.py
As mentioned in the issue #4892
> search entry box is cleared with escape key in
* neighbourhood view,
* friends view, and;
* home view (list and circle),
>
but not in journal.
when a journal entry is expanded, the escape key returns to the main journal view. (_key_press_event_cb in journalactivity.py)
please also clear the search entry. ;-)
Regards
=> Clear journal search with escape key

extensions/deviceicon/battery.py
Right now it shows a full white battery when it's not present
more logical would be if its not showed.
This patch does that
=> Hide battery icon when battery is not present

extensions/cpsection/aboutme/view.py, extensions/cpsection/backup/view.py, src/jarabe/controlpanel/gui.py, src/jarabe/controlpanel/sectionview.py
The restart warning when committing a section view has a "Later" button, which keeps the changes but does not restart.
About Me and Backup control panels omit the button.
Let external control panels also omit the button.
(For example, http://dev.laptop.org/git/projects/olpc-switch-desktop)
=> add control panel section view deferrable property

src/jarabe/controlpanel/gui.py
A critical message appears in shell.log when a control panel section is removed from screen:
```(main.py:6713): Gtk-CRITICAL **: gtk_container_remove: assertion 'gtk_widget_get_parent (widget) == GTK_WIDGET (container) || GTK_IS_ASSISTANT (container)' failed```
There is no other effect of the message.
Fix the warning by checking the object is in the container before trying to remove it.
Since None can't be a child of the container, the check for None is redundant, so is removed.  (This complication requested by review on https://github.com/sugarlabs/sugar/pull/588).
Reproducer: choose My Settings, then any icon, such as About Me, then press ```ESCAPE``` key once.  Examine shell.log.
Replaces https://github.com/sugarlabs/sugar/pull/588
=> check before remove on control panel section end

src/jarabe/controlpanel/gui.py, src/jarabe/desktop/favoritesview.py, src/jarabe/desktop/homewindow.py, src/jarabe/model/session.py, src/jarabe/view/buddymenu.py, src/jarabe/view/keyhandler.py
A series of fixes for failure to logout, restart or shutdown, when an activity is hung.  See the individual commits for narrative detail.
To cause a logout failure alert, start Terminal, then start ```xclock``` or ```xterm```, then click on the Terminal and press Ctrl-Z, this sends a SIGSTOP to the child process. Now switch to home view or control panel and try to logout, restart, or shutdown.
Other methods are to send SIGSTOP to any activity process.
Other test cases:
- check there is a busy cursor during startup and it goes away once journal is ready,
- check there is a busy cursor during shutdown, restart, or logout, if there is enough time to see it,
- make an activity not respond, check the logout failure alert appears,
- click cancel on the alert, switch to the hung activity, unhang …
=> fixes for logout hang

data/org.sugarlabs.gschema.xml, extensions/cpsection/frame/model.py, extensions/cpsection/frame/view.py, src/jarabe/frame/eventarea.py
Replaces #601 
When sugar is run inside a window, the frame trigger is a very small
target to hit.  This can be improved by making the trigger area bigger,
however it is only needed in some environments, not those where sugar
is fullscreen.
Ticket URL  <https://bugs.sugarlabs.org/ticket/4835>
=> Add setting for frame trigger size, fixes #4835

src/jarabe/view/viewsource.py
On Fedora 18, scroll bars were missing, see [4903](https://bugs.sugarlabs.org/ticket/4903).  On Fedora 20, impossible arguments were given to X server, resulting in desktop instability, see [12872](http://dev.laptop.org/ticket/12872).
Regression introduced in 4be3f9e and [4273](https://bugs.sugarlabs.org/ticket/4273), in the SourceDisplay class, where a [GtkBox](https://developer.gnome.org/gtk3/stable/GtkBox.html) is inserted between the [GtkScrolledWindow](https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html) and any child.
Fix is
- remove GtkBox intermediary; unnecessary,
- add methods for managing a single child of the GtkScrolledWindow, which will be either a [GtkSourceView](https://developer.gnome.org/gtksourceview/stable/GtkSourceView.html) or a …
=> fix missing scroll bar in view source

.gitignore, bin/Makefile.am, bin/sugar-serial-number-helper, data/Makefile.am, data/org.sugar.serial-number.policy.in, extensions/cpsection/aboutcomputer/model.py, po/POTFILES.skip
On commodity x86 and x86_64 hardware the serial number is available to
root in /sys/class/dmi/id/product_serial, but Sugar does not run as
root, so per commit 612842c the string "Not available" is shown.
Add a polkit helper to read the serial number.
=> serial number helper

bin/sugar-install-bundle
Accept multiple bundles on the command line.
Was requested in 2011 by Thomas Gilliard, a solution was
proposed by me but was accepted ada284445e9a3ce96a0c9df4c299021254b0668d
without complete testing, and caused http://dev.laptop.org/ticket/11178
so it was reverted in a hurry.
=> sugar-install-bundle: multiple bundles

extensions/cpsection/background/view.py
An idle task for loading images may continue to run after apply or undo.
- save the source identifier for the idle task,
- wipe the source identifier when the idle task is finished,
- remove the idle task if it is still running on apply or undo.
Fixes [#4911](https://bugs.sugarlabs.org/ticket/4911).
=> background control panel, drop idle task

extensions/cpsection/background/view.py
Gio.Settings changes are memory and processor expensive, because the [instance persists](http://lazka.github.io/pgi-docs/Gio-2.0/classes/Settings.html#Gio.Settings) until the change is flushed to disk.
Extra changes were happening during button creation, and for every click of a button.  By default, the first button is created active by Gtk+.  (See [Gtk.RadioButton](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/RadioButton.html#Gtk.RadioButton)).
When the code tries to set another button as active, the clicked callback for the first button is triggered.  When followed by apply, this can lead to incorrect setting.
Changes in this patch are to:
- ignore callbacks for a button changing from active to inactive, by checking get_active(),
- suppress callbacks during button creation, by …
=> background control panel, alpha level callbacks

src/jarabe/frame/frame.py, src/jarabe/view/gesturehandler.py
When the frame key is pressed rapidly, some presses are ignored, because the animation position is used to determine if the frame is visible.
To fix,
- remove class _KeyListener as it is not required, see also 3e28f56,
- add a flag for whether the frame is wanted or not, self._wanted,
- add a toggle() method, which calls show() or hide() according to last known wanted state, and call it from the mouse enter corner or frame key press methods,
- do not test frame visibility in show() or hide(), depend on _wanted,
- in the gesture handler, use toggle() instead of show() or hide(),
Test case:
```
xdotool key F6 key F6 key F6
```
should be equivalent in final effect to
```
xdotool key F6
```
Fixes [#4806](https://bugs.sugarlabs.org/ticket/4806).
=> frame key double press consistency

src/jarabe/view/launcher.py
Reduce the pulsing icon launcher redraw area from full width of screen to maximum size of icon, by packing the icon into a horizontal box with a false fill flag.
Tested on XO-1 and XO-1.5 with Sugar 0.107.0 and Fedora 18.
https://bugs.sugarlabs.org/ticket/4914 (#1)
=> launcher, reduce redraw area

src/jarabe/model/filetransfer.py, src/jarabe/model/telepathyclient.py
If empathy is installed and the user is sent a file transfer (via
the journal), an empathy dialog will pop up asking the user where
to save the file (in the filesystem, not journal).  This conflicts
with the Sugar ui.
Fixes #4907  <https://bugs.sugarlabs.org/ticket/4907>
=> Claim file transfer channels, so empathy does not revieve them

extensions/cpsection/modemconfiguration/__init__.py, extensions/cpsection/webaccount/__init__.py
Settings icons in the control panel were not evenly distributed, on screens with 1200 pixels horizontal, because some icon titles were very long.
Remove "Configuration" and "Configure your".
(the words are redundant; everything in my settings is a configuration).
=> fix control panel layout

src/jarabe/view/keyhandler.py
Both frame and control panel are visible; by pressing F6 then
Alt-Shift-M.
Hide the frame when the accelerator is used, in the same way that the
buddy menu does hide the frame.
Regression introduced by e43d177.
=> Hide frame on control panel accelerator

extensions/deviceicon/audio.py, extensions/deviceicon/display.py, src/jarabe/desktop/networkviews.py, src/jarabe/journal/journaltoolbox.py, src/jarabe/journal/palettes.py
icon_size was changed to pixel_size, yet several references remained,
causing extra log data.
Previous #630.
=> Fix remaining icon_size references

data/org.sugarlabs.gschema.xml, src/jarabe/view/launcher.py, src/jarabe/view/pulsingicon.py
On some computers, the activity startup pulsing icon steals resources, increasing startup time.
Add a launcher-interval setting, and use it in pulsing icon.
Test case:
```
gsettings set org.sugarlabs.desktop launcher-interval 500
```
Then restart Sugar.  The pulsing icon should be slow.
Measurements:
On one of the oldest computers that Sugar is used, an OLPC XO-1, CPU usage of the X server and Jarabe were measured during launch of Moon activity using top(1):
- launcher-interval=50 ms, gave 42% usage,
- launcher-interval=100 ms, gave 21% usage,
- launcher-interval=500 ms, gave 8% usage,
- launcher-interval=1000 ms, gave 4% usage.
Test configuration was Fedora 18 with Sugar 0.107.0, and commit d349379 (launcher, reduce redraw area).
References:
- olpc-os-builder/v7.0 [xo1: reduce pulsing …
=> Configurable launcher pulsing icon interval

src/jarabe/desktop/homewindow.py
Sometimes after stopping an activity that was started new with the Alt
key, the visibility notify event is missed, and the favourites view is
without user colour because the Alt key is presumed to be down.
Workaround is to briefly press and release the Alt key, and the colours
return.
Fix is to abandon the visibility notify event, which also happens to be
deprecated, in favour of a timeout that checks for Alt key release.
Also refactored the common code for detecting the Alt key in an event.
=> fix resume mode alt key handling in favourites

src/jarabe/desktop/viewtoolbar.py, src/jarabe/model/desktop.py
Before the GConf to Gsettings port changing the homeviews names
was possible.
This patch adds the ability to change it again using gsettings
config, "view-label".
How to test:
Follow the instruction for "gsettings instructions for Sugar 102+" in
https://wiki.sugarlabs.org/go/Features/Multiple_home_views
and add the key "view-label" to the homeview you want.
This is a GCI task:
https://codein.withgoogle.com/tasks/4788542454628352/
=> Add the ability for change homeviews names

src/jarabe/frame/clipboardicon.py, src/jarabe/frame/frame.py
If a user starts a drag action, then the timeout is reset to 5 seconds, if necessary we can increase the timer to whatever value needed.
=> Add drag from notification to act like a clipboard entry

extensions/cpsection/frame/model.py, extensions/cpsection/frame/view.py, src/jarabe/frame/eventarea.py, src/jarabe/frame/frame.py
Use the Gio.Settings 'changed' signal to avoid having to restart Sugar when the frame control panel is used.
Also fixes an interesting problem on real hardware, see c92dcf3 for details.
Includes #620.
=> Avoid restart in frame control panel

src/jarabe/controlpanel/gui.py
Adds keyboard navigation to control panel.
We maintain a list of selected options from search results, detect the return key and if unambiguous result, open section view.
Does not autocomplete like home view search.
=> Control panel section keyboard activation

src/jarabe/desktop/favoriteslayout.py
* Fixes 5c3de755cb9848154347991fdb369a7ea41004ae
* Now the neighborhood icon placing will work on 32 bits computers
* Supercedes #640
=> Fixed neighborhood icon placing (commit 5c3de75) in 32 bits

src/jarabe/desktop/homewindow.py
This was not done explicitly before, however on Gtk3.19 this
must be done explicitly.  Grabbing focus on the key press event
means that the entry still records that key press.
Ticket URL  <https://bugs.sugarlabs.org/ticket/4930>
=> Focus homeview search entry on key press, fixes #4930

src/jarabe/controlpanel/gui.py, src/jarabe/desktop/activitieslist.py, src/jarabe/desktop/favoritesview.py, src/jarabe/desktop/groupbox.py, src/jarabe/desktop/homewindow.py, src/jarabe/desktop/meshbox.py, src/jarabe/main.py
- do not let the view children of the home window take focus; this
prevents redraw, proving it is the focus change causing #4914.2,
- as a side effect focus is always in the search box, so the blinking
cursor is turned off quickly,
However, breaks and makes harder any solution for two tickets:
https://bugs.sugarlabs.org/ticket/1969 (Keyboard navigability of the
Sugar UI) closed by Daniel Narvaez for being non-specific, and would
require visible focus rectangles to be restored.
https://bugs.sugarlabs.org/ticket/4891 (no journal accessibility keys)
which turns out to be mentioned already by 1969.
=> reduce home view redraw excess

src/jarabe/view/buddymenu.py
A fix for the issue #2702 (https://bugs.sugarlabs.org/ticket/2702)
=> Fix "Invite to <activity>" shown even for activities that don't support sharing

extensions/cpsection/aboutcomputer/view.py
Dolphins patrolling the south pacific microplastic gyre have observed that the value returned by 
```python
import time
print time.strftime('%Y')
```
appears to have changed, and research suggests it has something to do with human tradition, yet the About My Computer text has not changed.  Rather than understand the tradition, the following patch is proposed:
```bash
sed --in-place 's/2015/2016/g' extensions/cpsection/aboutcomputer/view.py
```
Thus a rightness is brought to the world, albeit in a small way.
=> About my computer: set copyright year 2016

src/jarabe/journal/listview.py
Fixes issue [#3146](https://bugs.sugarlabs.org/ticket/3146) . Now only icon of entry can be dragged. 
Below is the result.
=> Fixed #3146: Dragging a Journal entry drags the whole white entry bar instead of icon

src/jarabe/journal/journaltoolbox.py
As discussed with @samdroid-apps . I added a feature of toggled sorting order for list in the Journal. This will allow the list to be sorted in both ways.
=> Implemented toggled sorting order

src/jarabe/journal/listview.py
Fixed issue [#4940](https://bugs.sugarlabs.org/ticket/4940) renaming entries to blank or whitespace. Now  entry cannot be renamed to blank (or say whitespace). If tried the old name is retained.
=> Fixed Issue: #4940 Journal entries name can be renamed to blank

extensions/cpsection/language/view.py
The typo error of "writting" instead of "writing" fixed.
Fixed issue [#4942](https://bugs.sugarlabs.org/ticket/4942)
=> Fixed issue #4942 Typo in sugar

src/jarabe/controlpanel/gui.py, src/jarabe/controlpanel/sectionview.py, src/jarabe/frame/framewindow.py, src/jarabe/intro/window.py, src/jarabe/journal/journaltoolbox.py, src/jarabe/journal/keepicon.py
Required by https://github.com/sugarlabs/sugar-artwork/pull/86
In Gtk+ 3.20, you need to use the css name to select elements,
rather than the gtype name.  Therefore, these must be added.
The css name must be set before the class instances are created, as
it effects the class rather than the instance.  This is why it must
be places after the class definition.
=> Set css name for widgets

src/jarabe/journal/listmodel.py
Fixed the function name typo. Changed ```reconect``` to -> ```reconnect```
I have greped throughout the sugar-build, ```__reconect_updates_cb()``` is only used in this module.
=> renamed 'reconect' to 'reconnect'

src/jarabe/journal/listview.py
Fixed [#4947](https://bugs.sugarlabs.org/ticket/4947)  . The palette was created when the cursor hovered in the buddy column even though there was no buddy icon at cursor position!
=> Fixed #4947: Buddy palette appears in wrong position

src/jarabe/controlpanel/gui.py
Fixed the issue where custom message for restart options, set through
'self.restart_msg = _('Your custom message')' in case of
'self.needs_restart'  set to True was not getting displayed and instead
the default 'Changes require restart' was displayed.
This was solved by simply passing the 'self.restart_msg' variable in
/jarabe/controlpanel/sectionview.py to 'alert.props.msg' variable in
/jarabe/controlpanel/gui.py where it is finally displayed.
=> Fix custom restart message display in control panel

src/jarabe/model/brightness.py
On systems with no brightness control, such as an XO-1 with kernel
4.6-rc1 due to 82ef33af9dd30075adbd9f3dd161b606b8ba88ac, Sugar does
crash on start with this shell.log fragment;
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/lib/python2.7/site-packages/jarabe/main.py", line 428, in <module>
main()
File "/usr/lib/python2.7/site-packages/jarabe/main.py", line 410, in main
brightness.get_instance()
File "/usr/lib/python2.7/site-packages/jarabe/model/brightness.py", line 30, in get_instance
_instance = Brightness()
File "/usr/lib/python2.7/site-packages/jarabe/model/brightness.py", line 53, in __init__ …
=> Fix brightness restore crash

src/jarabe/desktop/activitieslist.py, src/jarabe/journal/listview.py
Issue: Background of multiple cellrendericons in column rendered while scrolling
Link to issue on tracer: https://bugs.sugarlabs.org/ticket/4957
Fixed: Connected scroller to cellrenderericon using the connect_to_scroller() method in sugar3.graphics.icon.py
Issue ->
=> Fixed background render of cellrenderericon while scrolling

src/jarabe/desktop/activitieslist.py
This  patch add this requested feature -> https://bugs.sugarlabs.org/ticket/4919
Now the user can start an activity by just single clicking the row in the list view.
=> Start activity on single-clicking the corresponding row

src/jarabe/desktop/activitieslist.py
This  patch add this requested feature -> https://bugs.sugarlabs.org/ticket/4919
Now the user can start an activity by just single clicking the row in the list view.
=> Start activity on single-clicking the corresponding row #680

extensions/deviceicon/battery.py
_(this is the updated commit message from 67ffe98)_
Frame battery device is static on Ubuntu 16.04, with UPower 0.99.4.
The 'changed' signal is not sent.  UPower had deprecated 'changed', replacing with 'notify' for all properties, or on per-property basis.
* switch to UPowerGlib GObject introspection API,
* continue to use 'changed' signals on older UPower, for compatibility with OLPC OS 13.2.7, Fedora 18, UPower 0.9.19,
- switch to 'notify' signals if they are present,
- continue to use D-Bus API to get device path, because the older UPower fails on get_devices method, and doesn't have get_display_device,
- ignore bursts of notify signals; reduces frame icon redraws,
- fixes https://bugs.sugarlabs.org/ticket/4781.
Tested with OLPC OS 13.2.7 on XO-4, and Ubuntu 16.04 on commodity …
=> Fix for battery device icon update

data/org.sugarlabs.gschema.xml, extensions/cpsection/network/__init__.py, extensions/cpsection/network/view.py, src/jarabe/controlpanel/gui.py, src/jarabe/controlpanel/sectionview.py, src/jarabe/main.py
Add GUI based proxy manager in the Network section of 'My Settings' to
enable management of manual proxy servers.
The proxy settings are stored in /etc/profile.d/proxy.sh as exports to
environment variables and requires re-login to let the changes take effect.
/extensions/cpsection/network/set_proxy.py file writes the proxy settings,
while two polkit policy files org.sugar.proxy.policy and org.sugar.logout.policy
located at /usr/share/polkit-1/actions provide root permissions required
for file handling and logout command. These two polkit files are placed at
data/ directory of this repository.
=> Add manual proxy settings manager in network settings

src/jarabe/main.py
Because of the delay imposed by compositing, on particularly fast hardware, it also causes a breakthrough of home view between launcher and activity window mapping.
=> metacity shouldn't use compositing

src/jarabe/journal/listview.py
Was introduced in 265353af21f306e5b6316110c8b4d3e0a9e21b07 and does not seem to serve a purpose.
=> Remove log noise in Journal List View

src/jarabe/desktop/activitieslist.py
Sugar 0.109.0 fails to start on Fedora 18, due to an activity start on single click feature by @iamutkarshtiwari in 161254959a8431686ec5a1a26657a34f96267ecc and 3e951d96cae6c8fd95e8849c21f3782d11dd9524.
The feature is ported to Gtk+ 3.6.  See commit messages for more detail.
=> Repair activity start on single click on list view

bin/Makefile.am, bin/sugar-erase-bundle, src/jarabe/model/bundleregistry.py
Add sugar-erase-bundle next to sugar-install-bundle.
Expose system activity after user erase; when a user activity is erased using "rm -rf" or sugar-erase-bundle, any system activity was not exposed.  Handle a FileMonitorEvent.DELETED by also looking for the same activity in the system activity directories.
=> Erase bundle fixes

data/org.sugarlabs.gschema.xml
This allows for better activity support on newer systems, better
speed and privacy amongst other reasons.  It will not break
exsisting XO or schoolserver workflows.
The changes was discussed in [1].
[1]  http://lists.sugarlabs.org/archive/sugar-devel/2016-January/051187.html
@tchx84 is this ok for 108?
=> Set default collaberation model to salut (no jabber server)

src/jarabe/desktop/keydialog.py
This fixes the issue - https://bugs.sugarlabs.org/ticket/4963
Now the user can toggle the password visiblility via 'show password' checkButton provided
=> Password visibility toggle

src/jarabe/frame/eventarea.py
I believe that Gdk.drag_status (new function) has been here forever (tested fc25, fc22), since it doesn't have an "new since" section in the docs [1].
[1]  https://developer.gnome.org/gdk3/unstable/gdk3-Drag-and-Drop.html#gdk-drag-status
=> Fix drag_status call to work on fc24/23, fixes #4949

src/jarabe/frame/activitiestray.py, src/jarabe/model/invites.py
Currently, only the activity name is displayed.  This could be
confusing - "what is this write activity that you just invited me
to?  is it the kangaroo project, or the dolphin project?"
This commit displays the title as the palette secondary text, which
is consistent with how running activities are displayed in the frame.
After:
Before... the same, but it didn't say "Kangaroo Project Chat"
=> Display activity instance title in join requests

extensions/cpsection/language/model.py
Sugar should not misrepresent the system language list.
Will be added back as a packaging patch by OLPC OS if required for any future release.
References:
* http://lists.sugarlabs.org/archive/sugar-devel/2016-July/053245.html by @icarito 
* https://github.com/sugarlabs/sugar/pull/550#issuecomment-118431549
=> Remove Dari and Guarani languages workaround

src/jarabe/main.py
Gtk 3.20 recently changed the default setting so that buttons hide
their icons.  This is regression in terms of the Sugar HIG.
=> Show icons in buttons

extensions/deviceicon/frame.py, src/jarabe/main.py, src/jarabe/model/keyboard.py, src/jarabe/util/downloader.py, src/jarabe/view/viewhelp.py, src/jarabe/view/viewsource.py
Replaces #600, no longer assumes Maliit is installed.
Gi has been emitting warnings into the log to do this for some
time now.  Not doing this has also caused bugs, such as #4900.
Ticket URL <https://bugs.sugarlabs.org/ticket/4900>
=> Specify library version prior to import, fixes #4900

data/org.sugarlabs.gschema.xml, src/jarabe/desktop/favoritesview.py, src/jarabe/desktop/homebox.py, src/jarabe/desktop/homewindow.py
A new boolean value is now added to gsettings to toggle the default start mode of an activity from home view-
1) If the value is TRUE- Resumed instance opens
2) the value is FALSE - New instance starts
This GSetting value can be toggled from terminal by the following command - 
**$ gsettings set org.sugarlabs.user resume-activity false** (This sets the home view to start the new instance of every activity)
**$ gsettings set org.sugarlabs.user resume-activity true**  (This sets the home view to resume the instance by default)
=> Resume Activity Gsettings

extensions/deviceicon/display.py
Moving the brightness slider in the display frame device did not change
the brightness promptly, so it was difficult for the user to choose a
brightness.
Decrease the timeout, therefore increasing the responsiveness.
OLPC note: has been sent to manufacturing of SKU400.
=> Brightness: make frame device more responsive

src/jarabe/desktop/keydialog.py
Sugar 0.109.0.1 and 0.109.0.2 cannot connect to new secured networks.  The wireless password prompt does not appear.  Saved passwords made with 0.109.0.0 and earlier continue to work.
This regression was introduced in #693 commit dca2f17b8dd16adcff0ec98dc0ee63f8c8dce38b, and was apparently not tested in the form it was committed.
Also in this pull request;
- ensure "Show Password" can be translated,
- default to show the password, as per consensus in #693 and the default in 0.108,
- simplify and improve code style,
- remove an unnecessary call to the Gtk.Widget.show() method.
See individual commits for full details.
=> Wireless password fixes

data/activities.hidden
The OLPC library bundles and several activities appear in the activity
ring as favourites; they did not appear previously.
The OLPC library bundles have not changed for several years, and are
effectively a deprecated feature.  They are not included in our Ubuntu
builds, where we use the Wikipedia activity instead.  Adding them to the
list should have no impact on Ubuntu or Fedora SoaS.
ImageViewer, Jukebox, and Read activities were originally hidden.  Sugar
recently exposed them as a result of the enhanced favourites
patches (#4841).  Adding them to the list will hide them.
TamTamEdit, TamTamJam, and TamTamSynthLab were originally hidden.
=> Enhanced favourites: hidden bundles

extensions/cpsection/updater/view.py, extensions/deviceicon/network.py, src/jarabe/frame/activitiestray.py, src/jarabe/journal/journalactivity.py, src/jarabe/journal/volumestoolbar.py, src/jarabe/view/palettes.py
Sugar used ambiguous units for number of bytes.  Since then, the units have been standardised internationally.
- change MB to MiB,
- change KB to KiB,
- separate quantity and units for activities tray transfer palette,
- fix spelling of _SPACE_TRESHOLD, to be _SPACE_THRESHOLD,
- change units of _SPACE_THRESHOLD to MiB.
References:
- https://en.wikipedia.org/wiki/IEEE_1541-2002
- http://physics.nist.gov/cuu/Units/binary.html
- https://en.wikipedia.org/wiki/ISO/IEC_80000
=> IEC 80000-13:2008 and IEEE 1541-2002 compliance

src/jarabe/journal/objectchooser.py
With Sugar 0.109.0.2 several activities can no longer use the ObjectChooser; it does not appear, and logs show;
```
File "/usr/share/sugar/activities/Labyrinth.activity/src/MMapArea.py", line 323, in button_release
if not obj.process_button_release(event, coords):
File "/usr/share/sugar/activities/Labyrinth.activity/src/ImageThought.py", line 139, in process_button_release
if not self.journal_open_image():
File "/usr/share/sugar/activities/Labyrinth.activity/src/ImageThought.py", line 65, in journal_open_image
result = chooser.run()
File "/usr/lib/python2.7/dist-packages/sugar/graphics/objectchooser.py", line 87, in run
self._chooser_id = journal.ChooseObject(self._parent_xid, what_filter)
File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, …
```
=> Fix ObjectChooser without parent

extensions/cpsection/network/model.py, src/jarabe/desktop/networkviews.py, src/jarabe/model/network.py
The neighbourhood view uses icon badges to mark networks that are either locked or have been connected to.
The locked badge is lost when a network is connected to.  Fix is to add a new badge for locked and connected to.  Requires https://github.com/sugarlabs/sugar-artwork/pull/92.
The connected to badge is not removed promptly when the connections are discarded using the control panel.  Fix is to connect a removed signal and update the icon badge.
p.s. a patch for making discard testing faster by adding it to the buddy menu can be found at http://dev.laptop.org/~quozl/z/1bPOj7.txt
=> Wireless icon badge consistency

src/jarabe/desktop/networkviews.py, src/jarabe/model/network.py
_(Apologies, but this pull request was held up waiting for #704 to merge.)_
Once a wireless network is connected to, Sugar persists in trying to connect next time it starts.  Workaround is to "Discard wireless connections" in network control panel.
Add a forget menu item to the wireless network icons.
----
After this patch was written, an alternate implementation was found in https://bugs.sugarlabs.org/ticket/2264 written by Ezequiel Pereira (@ezequielpereira) during Google Code-in 2014, that had not been merged:
https://bugs.sugarlabs.org/attachment/ticket/2264/0001-Added-Forget-option-to-network-menu.patch
Ezequiel's patch seems to go a bit further than necessary, and brings the connection deletion into networkviews.py.  It may also need rebasing.
=> Wireless right-to-forget #2264

src/jarabe/journal/journalactivity.py, src/jarabe/journal/journaltoolbox.py, src/jarabe/journal/listview.py, src/jarabe/journal/projectview.py
Empty new project entry after creating new project
Currently, there is no direct feedback that the creation has succeeded,
so the user might create the project too many times.
Fix projects list view add new bar hiding
Steps to reproduce:
1.  Go to the projects list view
2.  Go to the details view for a project
3.  Click the back button
4.  Notice that the "add new project" bar has disappeared
Move AddNewBar logic for activation into the class
Previously, it was copied throughout the users of the class code.
Only activate add new bar with title typed in
Currently, the add new bar will always activate if the user presses
enter, even if there is no title typed in yet.  This makes it easy to
accidentally press enter twice and create 2 new projects.
Bind project list view to auto refresh
The …
=> Project view fixes

src/jarabe/intro/agepicker.py
When language is set to Spanish, the icons do not appear evenly spaced.
Each age is a Gtk.Grid containing an EventIcon and a Gtk.Label, but the array of grids is held in a Gtk.Fixed with spacing set by `_configure` method.  The design depends on the label fitting within the large icon size of the style.
Wrap and centre the label.  This increases the chance that it will fit within the large icon size.
Reported in https://bugs.sugarlabs.org/ticket/4967
=> About me - fix age picker spacing

extensions/deviceicon/battery.py, extensions/deviceicon/frame.py
- new version warning caused by new dependency on UPowerGlib in 495b216,
- new traceback caused by 171cddb, an unhandled exception.
=> Fix require_version messages in shell.log

src/jarabe/desktop/favoritesview.py, src/jarabe/desktop/homewindow.py, src/jarabe/journal/journalwindow.py
This patch set allows to run Sugar as a root window handler.
To try using osbuild, first apply patch then:
```
$ ./osbuild shell
$ build
$ sugar
```
You should see the Sugar home window use your desktop workarea, like this:
=> Homewindow desktop component

extensions/cpsection/network/model.py
```
/usr/share/sugar/extensions/cpsection/network/model.py:22:
PyGIWarning: NMClient was imported without specifying a version first.
Use gi.require_version('NMClient', '1.0') before import to ensure that the
right version gets loaded.
from gi.repository import NMClient
```
=> Control Panel - Network, remove warning

src/jarabe/journal/journalactivity.py
In 0.108 and earlier, the edit toolbar is shown when journal items are selected.
In 0.110 the edit toolbar does not appear, so operations such as batch erase are not available.
Regression was probably introduced by 8be8b2a ('Bind project list view to auto refresh') and other patches since 0.108.
References:
https://wiki.sugarlabs.org/go/Features/Multi_selection (2013)
=> Fix for journal batch operations

po/POTFILES.in
This did cause `make distcheck` to fail, causing RPM build to fail.
@leonardcj, take note.
@samdroid-apps, please use the `distcheck` target, and abort if exit status is non-zero.
References:
* https://wiki.sugarlabs.org/go/Development_Team/Release
* https://wiki.sugarlabs.org/go/Development_Team/Code_guidelines#Tools
=> Add missing POTFILES.in reference

src/jarabe/view/viewsource.py
File "/usr/lib/python2.7/site-packages/jarabe/view/viewsource.py", line 689, in __cursor_changed_cb
store, iter_ = selection.get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
No translation impact.
=> View source: remove warning

src/jarabe/view/viewsource.py
View Source was unable to find the toolkit.
site-packages is a Fedora specific path.
dist-packages is the Debian and Ubuntu equivalent.
=> View Source - distribution specific paths

src/jarabe/view/customizebundle.py
Logger name was inherited from another file.
=> Customise Bundle - fix logger name

src/jarabe/desktop/homebox.py
FavoritesBox was referenced as favoritesview, yet ActivitiesList was directly imported into the namespace.
Simplifies reading of the code.
=> Fix inconsistent HomeBox imports

src/jarabe/model/desktop.py
On the home view, the label of the ring icon is "Favorites view 1", even when there is only one view.  One view is the default.  There is no GUI for changing the number of views.
Regression introduced by c5b0905916519927c35396a857bfe983b4912ea0.
Suppress the suffix when only one view is available.
=> Favourites view number unnecessary

src/jarabe/journal/listview.py
When erasing all items in the journal using multi selection feature, "Your Journal is empty" is correctly displayed, but a traceback is in shell.log;
```
File "/usr/lib/python2.7/site-packages/jarabe/journal/listview.py", line 515, in __model_ready_cb
self._show_message(_(show_message_text),
UnboundLocalError: local variable 'show_message_text' referenced before assignment
```
Indentation was wrong; caused by 92f7af4.
Use of gettext was wrong; cf648ef and 92f7af4 added string constants that were not wrapped, instead a variable was wrapped.
@leonardcj, note internationalisation impact, because two new strings are added.
=> Journal batch erase: fix traceback

src/jarabe/journal/model.py
Since 0.106.0 and possibly earlier, `datastore.log` always contains
```
1476242752.500065 WARNING root: Unknown term: 
dbus.String(u'mountpoints')=dbus.Array([dbus.String(u'/')],
signature=dbus.Signature('s'), variant_level=1)
```
The datastore does not deal with the term mountpoints.  So filter the query before sending it.
=> Fix for datastore.log noise

extensions/cpsection/network/model.py
The control panel network radio button does nothing.  Occurs on Ubuntu 16.04 with NetworkManager 1.2.2.  Does not occur on Fedora 18.
Using the same API in a Python shell works fine.  The difference is that the object is rapidly discarded within the function.
Retaining the NMClient object fixes the problem.  Perhaps the NM API has changed to an asynchronous thread.
=> Fix radio off button

src/jarabe/desktop/favoriteslayout.py
When a 1366x768 embedded panel is used with a 1600x1200 external VGA display a Unity system settles on a clone resolution of 1024x768.  When Sugar resizes from 1366x768 to 1024x768 the activity ring dimensions are not renegotiated, and the ring is overlarge, hiding the tops of icons under the top bar.
Cause was reading the screen dimensions once instead of every time the size allocation is needed.
=> Fix for overlarge activity ring

src/jarabe/desktop/favoriteslayout.py
In network neighbourhood and activity random view, the icons did sometimes move into a collision with another icon.
Cause was resolution of collision was not offset by the vertical allocation.
Fix is to add the vertical allocation.
----
A useful test case is to select the activity random view, then move the Browse icon by drag and drop so that it collides with another icon.  Expected result with the patch is that the other icon will move out of the way, using the shortest escape path.  Observed result without the patch is that the other icon will move somewhat unpredictably and may end up in collision with the Browse icon, especially if the shortest escape path would have been downward.
=> Fix collision resolution in random view

src/jarabe/journal/objectchooser.py
This reverts a series of three commits;
* cadac88c1c880708bd2afe0e82a2c2356c4bd9df
* 0ba3171a3a5c92698a89553bdfa541c83e520694
* 739993b2c4e12faa33e6714a42e500c5d80fbb9f
On both Fedora 18 and Ubuntu 16.04, the series renders classroom laptops useless in minutes or hours, because any activity that opens the object chooser does fail to exit on quit, and processes leak and build-up on the system until memory is depleted. Evidence of the problem is shown by ps(1). Workaround is to reboot.
Reverting the series fixes the problem.
Handling the `Wnck.Screen` `window-close` signal in the same way as the original code does not fix the problem.
Commit cadac88 doesn't say why the change was made, and doesn't appear to add any functionality, so reverting seems the safest option.
=> Revert "Refactor journal.objectChooser according to popup module in toolkit-gtk"

src/jarabe/desktop/homewindow.py
When an external monitor is connected or disconnected, about 25% of the time the Sugar shell does not resize correctly; a `size-changed` signal occurs but the workarea geometry has not changed.
Underlying problem is an update race in `get_monitor_workarea`, so the fix is to call `get_monitor_geometry` for obtaining the width and height, but continue to use the workarea offset for the later call to `self.move()`.
Can be reproduced easily without an external monitor by switching display panel resolution repeatedly;
```
xrandr --output eDP1 --mode 1024x768
xrandr --output eDP1 --mode 1366x768
```
Part of a fix for https://bugs.sugarlabs.org/ticket/4968
----
Rename size changed callback.  Callbacks are to be named according to the signal, or the purpose to which we put the signal.  This …
=> Fix screen resize race

src/jarabe/main.py, src/jarabe/view/Makefile.am, src/jarabe/view/viewhelp.py, src/jarabe/view/viewhelp_webkit1.py, src/jarabe/view/viewhelp_webkit2.py
Always we see a warning about JavaScriptCore not being right version, caused by `main.py` requiring WebKit yet `viewhelp.py` requiring WebKit2.
Seems to be no reason not to support WebKit in addition to WebKit2 in the same code base.  Toolkit already supports both.
- remove `gi.require_version` from `main.py`,
- strip browser specific code from `viewhelp.py`,
- add new Browser base classes, one for WebKit, one for WebKit2,
- avoid `GdkX11.X11Window.foreign_new_for_display` if _xid_ unknown,
- recognise which browser class to use based on OLPC OS release.
=> View Help - Backport to WebKit and WebKit2

src/jarabe/journal/palettes.py
According to this issue: https://bugs.sugarlabs.org/ticket/4971 when erasing multiple journal entries, clicking on "Continue" while the erase is in process stalls it.
This removes the "Continue" button while the process is being performed. Please do let me know if this is fine or if this causes any repercussions. Thanks :)
=> Removes continue button while erasing multiple journal entries. Fixes #4971

data/org.sugarlabs.gschema.xml, extensions/deviceicon/battery.py
- intended to avoid filesystem corruption, which can occur if the
learner allows a laptop to run until the battery is empty,
- other desktop environments implement a similar feature,
- a grace time of one and a half minutes since Sugar start is so that
settings can be changed by an expert user,
- settings are not exposed to the learner,
- shell.log shall contain evidence of forced shutdown.
=> Force shutdown before battery is gone

src/jarabe/journal/palettes.py
Displayed selected entry count was not updated when an entry was erased.
Fixes #4972, https://bugs.sugarlabs.org/ticket/4972
(See also #743 for previous discussion).
=> Update selected count on journal entry erase

src/jarabe/journal/listview.py
This reverts commit e05452a571ef9366b2e44d3c9c28d1b6182c4b50 as the current behaviour is inconsistent across Sugar.
An journal entry title does not need to be non-blank; the learner should be allowed to use a blank or empty title.  The title can always be changed again.
The default title is never blank.  The title does not need to be unique; it is not a file name.
Reference:
https://bugs.sugarlabs.org/ticket/4940
=> Revert "Fixed Issue: #4940 Journal entries name can be renamed to blank"

data/org.sugarlabs.gschema.xml, src/jarabe/intro/window.py
This will disable asking for gender on startup. Selecting gender will still be available in the About Me section of the settings, however it won't be required. I also set the default age selection icons used (when a gender isn't set) to use the 'male' icons since the clothing there is more generic. 
Fixs #770
=> Don't ask for gender on default

src/jarabe/desktop/favoritesview.py
**Fixed in this PR:** #785  Home view still shows Browse if show_launcher = no 
**Reason of issue:**
- Due to difference in implementation in `_add_activity` function of favorites view and list view
**Tested on:**
1. Sugar 0.112, rdesktop, Ubuntu 16.04
2. Sugar 0.112 Desktop (no virtualEnv)
=> [Fix]: #785 Home view unaffected by show_launcher value

src/jarabe/journal/listview.py
**Fixed in this PR:** 
- star state does not toggle when the window has only one entry [#4944](https://bugs.sugarlabs.org/ticket/4944)
**Explanation of the issue:**
- For only one entry, on clicking the favorite icon, `clicked` signal was emitted, `_favorite_clicked_cb` was called, and `self._model` was updated, but the display was not updated
**Changes made:**
- If there is only one entry in the journal, call `_do_refresh` from `_favorite_clicked_cb`
**Investigation:**
- `_favorite_clicked_cb` is called
- The `cell_rect` values are correct
- `Triple clicking`(odd clicks) updates the icon. Essentially, more than one simultaneous click updates the display. Could be similar to what @quozl explained [here](https://bugs.sugarlabs.org/ticket/4904#comment:6)
=> Fix: Toggle Favorite star when there is only one entry

docs/development-environment.md
[sugar-docs/godiard-enable-debug](https://github.com/sugarlabs/sugar-docs/tree/godiard-enable-debug) can be safely removed in favor of thiis
=> Add changing debug level to docs

po/sugar.pot, src/jarabe/controlpanel/cmd.py, src/jarabe/frame/activitiestray.py, src/jarabe/view/alerts.py
Fixes #807 
**Changes:**
i) In the .`py` files that generated the warnings, the unnamed arguments were resolved with a direct mapping based on what was being translated.
**Result:**
i) The warnings no longer occur. Also i have modified the `po/sugar.pot`file.
=> Localize unnamed arguments with named arguments and mapping

src/jarabe/view/alerts.py
After building, sugar fails to run with error
```
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/local/lib/python2.7/dist-packages/jarabe/main.py", line 73, in <module>
from jarabe.view import keyhandler
File "/usr/local/lib/python2.7/dist-packages/jarabe/view/keyhandler.py", line 32, in <module>
from jarabe.journal import journalactivity
File "/usr/local/lib/python2.7/dist-packages/jarabe/journal/journalactivity.py", line 37, in <module>
from jarabe.journal.journaltoolbox import MainToolbox
File "/usr/local/lib/python2.7/dist-packages/jarabe/journal/journaltoolbox.py", line 49, in <module>
from …
```
=> Fix syntax error

docs/development-environment.md
Explain how to build a development environment for both versions of Python.
Depends on patch
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/411/commits/bf057be3baefc99325678113b2d889e1dbdf83fa
and pull request
https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/411
Signed-off-by: James Cameron <quozl@laptop.org>
@Aniket21mathur, please review.
=> Build for either python 2 or python 3

docs/development-environment.md
Changes to documentation of native environment made while setting up Sugar on
* Fedora 30, and;
* Ubuntu 19.04
with downstream packages of Sugar in `/usr`, and our packages in `/usr/local`,
=> Docs - test Fedora native environment

docs/development-environment.md
Installing toolkit for python3 makes the sugar3 directory in site-packages
while the call is made from dist-packages. So there is a need to move sugar3
directory from site to dist.
=> Updates regarding sugar3 in site-packages.

extensions/cpsection/backup/view.py, extensions/deviceicon/audio.py, extensions/deviceicon/display.py, extensions/deviceicon/speech.py, src/jarabe/controlpanel/gui.py, src/jarabe/desktop/activitieslist.py, src/jarabe/frame/clipboardicon.py, src/jarabe/frame/clipboardpanelwindow.py, src/jarabe/frame/eventarea.py, src/jarabe/journal/journaltoolbox.py, src/jarabe/model/session.py
GLib accepts signal names with dash or underscore, and documents the
signals with a dash.
Use of GLib signal names in Sugar was mixed.
Change to using the dash.
No functional change.
Not tested.
=> Dash in signal names

configure.ac, data/Makefile.am
Fixes #882 
Fixes #896
Fix makefile dependency on /usr/bin/empy for Linux distributions which do not package a empy binary executable.
In comparison to @aperezbios 's patch on #896, I have tried to call 
`python3 -m em` so that the
* the `em` wherever located should be called
* Fixes the dependency on Linux distros that doesn't have the `x` flag set on the python files.
I am not sure if what I have attempted to fix is with regards in the Coding guidelines. The semantics seems correct, I have tested it. Works satisfactorily. 
Please review @quozl @aperezbios @tchx84
=> Depend on empy python module

src/jarabe/model/buddy.py
Steps to produce - open a fructose activity such as write on VM , click on neighbourhood icon , join on other VM , then stop activities on both VMs.
=> TypeError : section names must be strings

extensions/cpsection/language/model.py
There was a decode() error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 7862: invalid continuation byte
Fixed by adding 'utf-8' and 'ignore' args to decode()
Not 100% sure that this is the only thing causing #941 but it is certainly part of the problem.
=> Possible fix to #941

src/jarabe/model/notifications.py
See https://specifications.freedesktop.org/notification-spec/latest/index.html, specifically the [GetServerInformation signature](https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html).
I didn't test this myself as I only found this by accident while reviewing different notification daemons. You can test it using `dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation` which will show a `TypeError` without this change.
=> notifications: Fix signature of GetServerInformation

src/jarabe/util/downloader.py
According to developer.gnome.org
> In the past, SoupSession was an abstract class, and users needed to choose between SoupSessionAsync (which always uses GMainLoop-based I/O), or SoupSessionSync (which always uses blocking I/O and can be used from multiple threads simultaneously). This is no longer necessary; you can (and should) use a plain SoupSession, which supports both synchronous and asynchronous use. (When using a plain SoupSession, soup_session_queue_message() behaves like it traditionally did on a SoupSessionAsync, and soup_session_send_message() behaves like it traditionally did on a SoupSessionSync.)
=> use Soup.Session instead of Soup.AsyncSession

docs/components.md
A Software bill of materials[^1] (SBOM) in prose form was constructed by looking through the source code[^2] for various means of dependence[^3].
[^1]: [Software bill of materials - Wikipedia](https://en.wikipedia.org/wiki/Software_bill_of_materials)
[^2]: Sugar, Sugar Artwork, Sugar Toolkit, Sugar Datastore, and the Fructose activities Browse, Calculate, Chat, Image Viewer, Jukebox, Log, Pippy, Read, Terminal, Turtle Art, and Write.
[^3]: Python imports, C #includes, and fork and exec code patterns.
=> Components of a Software Bill Of Materials (SBOM)

src/jarabe/journal/expandedentry.py, src/jarabe/journal/journalactivity.py, src/jarabe/journal/listview.py
@srevinsaju @quozl can you test?
This was moved from #663.
The comment made by @i5o here https://github.com/sugarlabs/sugar/pull/663#issuecomment-260526997 isn't a blocker as the `entry` doesn't handle when the `enter` key is pressed and I don't think it needs to, so pressing the `enter` key would have no effect.
=> Fixed issue:Journal Entries can be renamed to blank via DetailView

src/jarabe/frame/activitiestray.py, src/jarabe/frame/clipboardicon.py, src/jarabe/frame/clipboardmenu.py, src/jarabe/frame/clipboardtray.py
@quozl @srevinsaju kindly test and review.
Will fix object recopying to the clipboard after it's dragged and saved to the journal in another PR.
> It seems to have some weird conditions with drags from browse. If I drag an image from browse to the journal, it fails [1]. But if I go browse->clipboard then clipboard->browse it works.
This is still the case and I don't think it should change.
Seeing as this is a feature, would one commit be preferred?
=> Add drag from clipboard to journal to store data 

src/jarabe/desktop/favoritesview.py
This is a GCI task and requires to enable all the home views
that we already have coded.
=> favoritesview: enable all home view layouts

docs/ubuntu.md
For ubuntu 20.04, `sudo apt install sucrose` throws error: `Unable to locate package sucrose`. 
sucrose package available for versions: 
`jammy (22.04LTS) (metapackages): Sugar Learning Platform - Sucrose [universe] 0.118-2: all`
`lunar (23.04) (metapackages): Sugar Learning Platform - Sucrose [universe] 0.120-1: all`
`mantic (23.10) (metapackages): Sugar Learning Platform - Sucrose [universe] 0.120-1: all`
`noble (metapackages): Sugar Learning Platform - Sucrose [universe] 0.120-1: all`
=> Update ubuntu.md about currently available sucrose package in Ubuntu

src/jarabe/journal/model.py, src/jarabe/view/customizebundle.py
Call xdg-user-dirs-update to update xdg directories before looking for any user directory.
@kshitijdshah99 kindly test and review, you can test with Pippy activity, you'll need to build sugar
with this branch to test.
Before this change `ActivityToolbarButton -> Create a Sugar activity Bundle` threw an error, this fixes that.
=> Fix incomplete port to python3
